#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

# branches to build
branches:
  # whitelist
  only:
    - master
    
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build + test + package +publish
image: Previous Visual Studio 2019

before_build:
  - cmd: nuget restore

build:
  project: HopfieldNetwork-DotNetCore.sln
  verbosity: detailed    

#---------------------------------#
#       tests configuration       #
#---------------------------------#    
after_test:     
# generate report for MSTest testing framework:
   - cmd :
        packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:HopfieldNetworkTesting/bin/debug/HopfieldNetworkTesting.dll" -output:coverage.xml
