#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

# branches to build
branches:
  # whitelist
  only:
    - master
    
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build + test + package +publish
image: Previous Visual Studio 2019

before_build:
  - choco install opencover.portable
  - cmd: nuget restore

build:
  project: HopfieldNetwork-DotNetCore.sln
  verbosity: detailed    

#---------------------------------#
#       tests configuration       #
#---------------------------------#    
before_test:
  - cmd: cd HopfieldNetworkTesting
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
  - cmd: cd ..
  - cmd: cd
  - cmd: C:\"Program Files"\dotnet\dotnet.exe test "C:\projects\hopfieldnetwork-dotnetcore\HopfieldNetworkTesting\HopfieldNetworkTesting.csproj"

after_test:
  - cmd: OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\hopfieldnetwork-dotnetcore\HopfieldNetworkTesting\HopfieldNetworkTesting.csproj" -output:coverage.xml