#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

# branches to build
branches:
  # whitelist
  only:
    - master
    
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build + test + package +publish
image: Previous Visual Studio 2019

before_build:
  - choco install opencover.portable
  - cmd: nuget restore

build:
  project: HopfieldNetwork-DotNetCore.sln
  verbosity: detailed    

environment:
  COVERALLS_REPO_TOKEN:
    secure: oquati3lPE6WsV2z6oClGkMqGoQ+O5v9b/kmlFh6kZjfw8tWufUyEOC6f3apx/9Z

#---------------------------------#
#       tests configuration       #
#---------------------------------#    
before_test:
  - cmd: cd HopfieldNetworkTesting
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
  - cmd: cd ..
  - cmd: nuget install coveralls.io -Version 1.4.2
  - cmd: cd
  - cmd: dir/b/s
  - cmd: C:\"Program Files"\dotnet\dotnet.exe test "C:\projects\hopfieldnetwork-dotnetcore\HopfieldNetworkTesting\HopfieldNetworkTesting.csproj" --test-adapter-path:. --logger:Appveyor

after_test:
  - cmd: OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\hopfieldnetwork-dotnetcore\HopfieldNetworkTesting\HopfieldNetworkTesting.csproj" -output:coverage.xml
  - cmd: coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%
  - cmd: dir/b/s
  - cmd: type C:\projects\hopfieldnetwork-dotnetcore\coverage.xml
  - cmd: type C:\projects\hopfieldnetwork-dotnetcore\HopfieldNetworkTesting\TestResults\results.trx